# Generated by Django 3.1.3 on 2020-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
